// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.3
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SchemaRegistryExamples.Avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.3")]
	public partial class ProductCreatedEvent : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ProductCreatedEvent"",""namespace"":""SchemaRegistryExamples.Avro"",""fields"":[{""name"":""Id"",""type"":""string""},{""name"":""Name"",""type"":""string""},{""name"":""Price"",""type"":""double""},{""name"":""Stock"",""type"":""int""},{""name"":""CategoryId"",""type"":""int""}]}");
		private string _Id;
		private string _Name;
		private double _Price;
		private int _Stock;
		private int _CategoryId;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ProductCreatedEvent._SCHEMA;
			}
		}
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				this._Name = value;
			}
		}
		public double Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				this._Price = value;
			}
		}
		public int Stock
		{
			get
			{
				return this._Stock;
			}
			set
			{
				this._Stock = value;
			}
		}
		public int CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				this._CategoryId = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.Name;
			case 2: return this.Price;
			case 3: return this.Stock;
			case 4: return this.CategoryId;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.String)fieldValue; break;
			case 1: this.Name = (System.String)fieldValue; break;
			case 2: this.Price = (System.Double)fieldValue; break;
			case 3: this.Stock = (System.Int32)fieldValue; break;
			case 4: this.CategoryId = (System.Int32)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
